server:
  port: 1111
eureka:
 # server:
    #enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    #表明这是一个server，而不是client
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server