spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: fkfczZzLNSpibHOhgk728tfJM6XG
#    password: 123
#    url: jdbc:mysql://localhost:3306/case-project?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#    url: jdbc:p6spy:mysql://192.168.10.51:3306/case-project?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://192.168.10.51:3306/case-project?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
# 指定文件上传路径
fileupload:
  uploadPath: D:\\upload
#  uploadPath: /home/monkey/upload
#  uploadPath: /root/upload


