spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL-USER:root}
    password: ${MYSQL-PWD:123456}
##    password: ${MYSQL-PWD:HANwl.83!}
    url: jdbc:mysql://${MYSQL-HOST:localhost}:${MYSQL-PORT:3306}/${MYSQL-DB:drive}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql://${MYSQL-HOST:192.168.10.51}:${MYSQL-PORT:3306}/${MYSQL-DB:iotplatform}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8

#    url: jdbc:mysql://129.204.3.98:3306/drive?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: EzoG8lFig1LZgOA4

# 指定文件上传路径
fileupload:
  uploadPath: D:\\upload
#  uploadPath: /home/monkey/upload
#  uploadPath: /root/upload


